

title: "TCSinger: Zero-Shot Singing Voice Synthesis with Style Transfer and Multi-Level Style Control"
layout: default
markdown: kramdown
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
kramdown:
  toc_levels: 1..2
