

title: "TransferSinger: Zero-Shot Singing Voice Synthesis with Style Transfer"
layout: default
markdown: kramdown
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
kramdown:
  toc_levels: 1..2
